/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.23
 * Generated at: 2016-02-25 18:02:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.apps.easymobile;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.unieap.UnieapConstants;
import com.unieap.pojo.User;
import com.unieap.base.SYSConfig;

public final class complain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/unieap/unieap.jsp", Long.valueOf(1450633063746L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.unieap.UnieapConstants");
    _jspx_imports_classes.add("com.unieap.base.SYSConfig");
    _jspx_imports_classes.add("com.unieap.pojo.User");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\" \"http://www.w3.org/TR/html4/strict.dtd\">\r\n");
      out.write("\r\n");
      out.write("\r\n");

	
    String path = request.getContextPath();
    String basePath = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort()
	        + path + "/";
    User user = UnieapConstants.getUser();
    Object error = request.getSession().getAttribute("SPRING_SECURITY_CONTEXT");
    String errorDesc = "";	
    if(error!=null){
		errorDesc = error.toString();
		if(errorDesc.contains("Bad credentials")||errorDesc.contains("UserDetailsService")){
			errorDesc = UnieapConstants.getMessage("user.login.error.usercode");
		}
	}
    

      out.write("\r\n");
      out.write("<!-- 开源框架文件\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.print(path);
      out.write("/unieap/js/ext-6.0.1/build/ext-all.js\"></script>\r\n");
      out.write("-->\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.print(path);
      out.write("/unieap/js/ext-4.2.1/ext-all.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/unieap/js/ext-4.2.1/locale/ext-lang-");
      out.print(SYSConfig.defaultLanguage);
      out.write(".js\"></script> \r\n");
      out.write("<!-- extjs框架文件 \r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(path);
      out.write("/unieap/js/ext-4.2.1/resources/css/ext-all-neptune.css\" />\r\n");
      out.write("-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(path);
      out.write("/unieap/js/ext-4.2.1/resources/css/ext-all-gray.css\" />\r\n");
      out.write("<!-- unieap框架文件 -->\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.print(path);
      out.write("/unieap/js/common/unieap.util.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(path);
      out.write("/unieap/js/common/css/common.css\" />\r\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"");
      out.print(path);
      out.write("/unieap/js/common/images/title.png\" media=\"screen\" /> \r\n");
      out.write("<!-- 快码缓存文件,由系统生成-->\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.print(path);
      out.write("/sharefolder/common/");
      out.print(user.getUserCode());
      out.write("_button_constants.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.print(path);
      out.write("/sharefolder/common/");
      out.print(user.getUserCode());
      out.write("_dicdata_constants.js\"></script>\r\n");
      out.write("<!-- 根目录路径 -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar basePathUrl = \"");
      out.print(basePath);
      out.write("\";\r\n");
      out.write("\tvar errorDesc = \"");
      out.print(errorDesc);
      out.write("\";\r\n");
      out.write("\tvar responseText = \"\";\r\n");
      out.write("\tExt.onReady(function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(errorDesc.indexOf(\"This session has been expired\")>-1){\r\n");
      out.write("\t\t\tExt.MessageBox.show({title: '");
      out.print(UnieapConstants.getMessage("comm.status"));
      out.write("',msg:'This session has been expired',width:120, height:100,\r\n");
      out.write("\t\t\t\tfn: showResult,buttons: Ext.MessageBox.OK,icon:Ext.MessageBox.WARNING});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tExt.Ajax.on('requestcomplete',function(conn, response, options, eOpts){  \r\n");
      out.write("\t\t\tresponseText = response.responseText;\r\n");
      out.write("\t\t\tif(responseText.indexOf('<script type=\"text/javascript\">')>-1){\r\n");
      out.write("\t\t\t\tExt.MessageBox.show({title: '");
      out.print(UnieapConstants.getMessage("comm.status"));
      out.write("',msg:'This session has been expired',width:120, height:100,\r\n");
      out.write("\t\t\t\t\tfn: showTimeOutResult,buttons: Ext.MessageBox.OK,icon:Ext.MessageBox.WARNING});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}else if(responseText.indexOf(\"This session has been expired\")>-1){\r\n");
      out.write("\t\t\t\tExt.MessageBox.show({title: '");
      out.print(UnieapConstants.getMessage("comm.status"));
      out.write("',msg:'This session has been expired',width:120, height:100,\r\n");
      out.write("\t\t\t\t\tfn: showResult,buttons: Ext.MessageBox.OK,icon:Ext.MessageBox.WARNING});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("        });\r\n");
      out.write("\t\tfunction showTimeOutResult(){\r\n");
      out.write("\t\t\tdocument.write(responseText); \r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction showResult(btn){\r\n");
      out.write("\t\t\t window.top.location.href = \"");
      out.print(path);
      out.write("/timeout.jsp\";  \r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write(" <style type=\"text/css\">\r\n");
      out.write("    .add {\r\n");
      out.write("\t    background-image: url(unieap/js/common/images/add.png) !important;\r\n");
      out.write("\t}\r\n");
      out.write("\t.delete {\r\n");
      out.write("\t    background-image: url(unieap/js/common/images/delete.png ) !important;\r\n");
      out.write("\t}\r\n");
      out.write("\t.edit {\r\n");
      out.write("\t    background-image: url(unieap/js/common/images/edit.png ) !important;\r\n");
      out.write("\t}\r\n");
      out.write("\t.save {\r\n");
      out.write("\t    background-image: url(unieap/js/common/images/save.gif ) !important;\r\n");
      out.write("\t}\r\n");
      out.write("\t.find {\r\n");
      out.write("\t    background-image: url(unieap/js/common/images/find.gif ) !important;\r\n");
      out.write("\t}\r\n");
      out.write("\t.search-trigger {\r\n");
      out.write("\t    background-image: url(unieap/js/common/images/search-trigger.png ) !important;\r\n");
      out.write("\t}\r\n");
      out.write("\t.clear-trigger {\r\n");
      out.write("\t    background-image: url(unieap/js/common/images/clear-trigger.gif ) !important;\r\n");
      out.write("\t}\r\n");
      out.write("\t.view {\r\n");
      out.write("\t    background-image: url(unieap/js/common/images/view.gif ) !important;\r\n");
      out.write("\t}\r\n");
      out.write("\t.money-up {\r\n");
      out.write("\t    background-image: url(unieap/js/common/images/money_add.png ) !important;\r\n");
      out.write("\t}\r\n");
      out.write("\t.money-down {\r\n");
      out.write("\t    background-image: url(unieap/js/common/images/money_delete.png ) !important;\r\n");
      out.write("\t}\r\n");
      out.write("\t.folder_go {\r\n");
      out.write("        background-image: url(unieap/js/common/images/folder_go.png) !important;\r\n");
      out.write("    }\r\n");
      out.write("    .menu-show {\r\n");
      out.write("        background-image: url(unieap/js/common/images/menu-show.gif) !important;\r\n");
      out.write("    }\r\n");
      out.write("    .buttons {\r\n");
      out.write("        background-image: url(unieap/js/common/images/buttons.gif) !important;\r\n");
      out.write("    }\r\n");
      out.write("    .leaf {\r\n");
      out.write("        background-image: url(unieap/js/common/images/leaf.png) !important;\r\n");
      out.write("    }\r\n");
      out.write("    .readonly_field{\r\n");
      out.write("\t\tbackground: white repeat-x 0 0;\r\n");
      out.write("\t\tbackground-color:#eaeaea;\r\n");
      out.write("\t}\r\n");
      out.write("\t.refresh {\r\n");
      out.write("\t    background-image: url(unieap/js/common/images/refresh.png) !important;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<!-- unieap用户权限文件 -->\r\n");
      out.write("<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("<meta http-equiv=\"expires\" content=\"0\">\r\n");
      out.write("<meta http-equiv=\"keywords\" content=\"mobile care,mobile service,self-service\">\r\n");
      out.write("<meta http-equiv=\"description\" content=\"unieap system\">\t\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no\">    \r\n");
      out.write("<meta name=\"format-detection\" content=\"telephone=no\" /> \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>complain management</title>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    function showPicture(url){\r\n");
      out.write("   \t\twindow.open(url);\r\n");
      out.write("   \t}\r\n");
      out.write("    Ext.onReady(function(){\r\n");
      out.write("    \tExt.tip.QuickTipManager.init();\r\n");
      out.write("    \t var queryPara;\r\n");
      out.write("    \t var queryform = Ext.create('Ext.form.Panel',{\r\n");
      out.write(" \t\t\tfieldDefaults:\r\n");
      out.write(" \t\t\t{ labelAlign: 'left', labelWidth: 70 },\r\n");
      out.write(" \t        layout: 'fit',\r\n");
      out.write(" \t        width : '100%',\r\n");
      out.write("      \t   \tframe : true,\r\n");
      out.write("      \t    items:[\r\n");
      out.write("      \t           { id:'queryFieldset', width: '100%',xtype:'fieldset',title: '");
      out.print(UnieapConstants.getMessage("comm.search"));
      out.write("',\r\n");
      out.write("   \t                 startCollapsed: true,collapsible: true, defaultType: 'textfield',\r\n");
      out.write("   \t                \titems:\r\n");
      out.write("   \t                \t\t[\r\n");
      out.write(" \t\t\t\t\t\t\t\t{ xtype: 'fieldcontainer',layout: 'hbox',\r\n");
      out.write(" \t\t\t\t\t\t\t\t\tdefaults : { \r\n");
      out.write(" \t\t\t\t\t\t\t\t\t\tmargins : \"5\" \r\n");
      out.write(" \t\t\t\t\t\t\t\t\t},\r\n");
      out.write(" \t\t\t\t\t\t\t\t    items: \r\n");
      out.write(" \t\t\t\t\t\t\t\t    [\r\n");
      out.write(" \t\t\t\t\t\t\t\t        { xtype:'textfield',name: 'submitBy',fieldLabel: '");
      out.print(UnieapConstants.getMessage("mcare.complain.display.submitBy"));
      out.write("'},\r\n");
      out.write(" \t\t\t\t\t\t\t\t        {name: 'submitDateStart', fieldLabel: '<font color=red>*</font>");
      out.print(UnieapConstants.getMessage("mcare.complain.display.submitDateStart"));
      out.write("',format: 'Y-m-d', xtype: 'datefield',allowBlank:false,\r\n");
      out.write(" \t\t\t\t\t\t               \t\tvalue:Ext.util.Format.date(Ext.Date.add(new Date(),Ext.Date.DAY,-1),\"Y-m-d\")\t\r\n");
      out.write(" \t\t\t\t\t\t               \t},\r\n");
      out.write(" \t\t\t\t\t\t                {name: 'submitDateEnd', fieldLabel: '<font color=red>*</font>");
      out.print(UnieapConstants.getMessage("mcare.complain.display.submitDateEnd"));
      out.write("', format: 'Y-m-d',xtype: 'datefield',allowBlank:false,\r\n");
      out.write(" \t\t\t\t\t\t               \t\tvalue:Ext.util.Format.date(Ext.Date.add(new Date(),Ext.Date.DAY,+1),\"Y-m-d\")\t\r\n");
      out.write(" \t\t\t\t\t\t                },\r\n");
      out.write(" \t\t\t\t\t\t                { xtype:'button',iconCls:'search-trigger',text:'");
      out.print(UnieapConstants.getMessage("comm.search"));
      out.write("',iconAlign: 'right',\r\n");
      out.write(" \t\t\t\t\t    \t                handler: function (){\r\n");
      out.write(" \t\t\t\t\t    \t                \tvar form = queryform.getForm();\r\n");
      out.write(" \t\t\t\t\t    \t                \tif (form.isValid()){\r\n");
      out.write("\t \t\t\t\t\t    \t                \tvar submitBy=queryform.getForm().findField(\"submitBy\").getValue(); \r\n");
      out.write("\t \t\t\t\t\t    \t                    var submitDateStart=dateFormat(queryform.getForm().findField(\"submitDateStart\").getValue()); \r\n");
      out.write("\t \t\t\t\t\t    \t                    var submitDateEnd=dateFormat(queryform.getForm().findField(\"submitDateEnd\").getValue()); \r\n");
      out.write("\t \t\t\t\t\t    \t                    queryPara = \r\n");
      out.write("\t \t\t\t\t\t    \t                    \t{\r\n");
      out.write("\t \t\t\t\t\t    \t                    \t\tsubmitBy:submitBy,\r\n");
      out.write("\t \t\t\t\t\t    \t                    \t\tsubmitDateStart:submitDateStart,\r\n");
      out.write("\t \t\t\t\t\t    \t                    \t\tsubmitDateEnd:submitDateEnd\r\n");
      out.write("\t \t\t\t\t\t   \t                        \t};\r\n");
      out.write("\t \t\t\t\t\t    \t                   gridstore.load({params:queryPara});\r\n");
      out.write(" \t\t\t\t\t    \t                \t}\r\n");
      out.write(" \t\t\t\t\t    \t                }\r\n");
      out.write(" \t\t\t\t\t\t                },\r\n");
      out.write(" \t\t\t\t\t\t                { xtype:'button',iconCls:'clear-trigger',text:'");
      out.print(UnieapConstants.getMessage("comm.reset"));
      out.write("',iconAlign: 'right',\r\n");
      out.write(" \t\t\t\t\t    \t                handler: function (){\r\n");
      out.write(" \t\t\t\t\t    \t                \tqueryform.getForm().reset(); \r\n");
      out.write(" \t\t\t\t\t    \t                }\r\n");
      out.write(" \t\t\t\t\t\t                }\r\n");
      out.write(" \t\t\t\t\t\t\t\t        \r\n");
      out.write(" \t\t\t\t\t\t\t\t    ]\r\n");
      out.write(" \t\t\t\t\t\t\t\t}\r\n");
      out.write(" \t\t\t\t\t  \t     ]\r\n");
      out.write(" \t\t\t\t\t     }\r\n");
      out.write("      \t           ]\r\n");
      out.write(" \t\t});\r\n");
      out.write("    \t \r\n");
      out.write("    \tExt.define('datamodel', {\r\n");
      out.write("            extend: 'Ext.data.Model',\r\n");
      out.write("            fields:\r\n");
      out.write("            [\r\n");
      out.write("            \t'id','evalution','text','url','fileName','submitDate','submitBy','feedback','status','statusDesc','modifyDate','modifyBy'\r\n");
      out.write("            ],\r\n");
      out.write("            idProperty: 'id'\r\n");
      out.write("        });\r\n");
      out.write("    \tvar gridstore = Ext.create('Ext.data.Store', {\r\n");
      out.write("            model: 'datamodel',\r\n");
      out.write("            pageSize: ");
      out.print(SYSConfig.getConfig().get("pageSize"));
      out.write(",\r\n");
      out.write("            remoteSort: true,\r\n");
      out.write("            proxy:{ type: 'ajax', url: 'easyMobileController.do?method=complainGrid',\r\n");
      out.write("                reader: \r\n");
      out.write("                {root: 'rows', totalProperty: 'totalCount'},\r\n");
      out.write("                simpleSortMode: true\r\n");
      out.write("            },\r\n");
      out.write("            sorters: [{ property: 'id', direction: 'DESC'}]\r\n");
      out.write("        });\r\n");
      out.write("    \tgridstore.on('beforeload', function (store, options){\r\n");
      out.write("            Ext.apply(store.proxy.extraParams,queryPara);\r\n");
      out.write("        });\r\n");
      out.write("    \t\r\n");
      out.write("    \tvar operationItems = [];\r\n");
      out.write("    \tvar selectedRecord;\r\n");
      out.write("    \tif(UnieapButton.Complain_Modify!=null&&UnieapButton.Complain_Modify.abled==true){\r\n");
      out.write("    \t\toperationItems.push({iconCls :'',tooltip:''});\r\n");
      out.write("\t    \toperationItems.push({\r\n");
      out.write("\t    \t\ticonCls : 'edit',\r\n");
      out.write("\t     \t   \ttooltip: '");
      out.print(UnieapConstants.getMessage("comm.modify"));
      out.write("',\r\n");
      out.write("\t           \thandler:function(grid, rowIndex, colIndex){\t\r\n");
      out.write("\t         \t   \tselectedRecord = grid.getStore().getAt(rowIndex);\r\n");
      out.write("\t        \t\tshowForm('Modify',selectedRecord);\r\n");
      out.write("\t           \t}\r\n");
      out.write("\t        });\r\n");
      out.write("    \t}\r\n");
      out.write("    \tvar selModel = Ext.create('Ext.selection.CheckboxModel');\r\n");
      out.write("        var datagrid = Ext.create('Ext.grid.Panel', \r\n");
      out.write("               {el : 'datagrid',layout: 'fit',columnLines: true,autoScroll:true,\r\n");
      out.write("       \t   \t \tselModel:selModel,\r\n");
      out.write("          \t   \tstore : gridstore,\r\n");
      out.write("       \t   \t   \tcolumns:\r\n");
      out.write("       \t   \t   \t[\r\n");
      out.write("\t\t\t\t\t{ menuDisabled: true,sortable: false, xtype: 'actioncolumn', text: \"");
      out.print(UnieapConstants.getMessage("comm.operation"));
      out.write("\",width:80,items:operationItems},\r\n");
      out.write("       \t   \t   \t\t{ text: \"");
      out.print(UnieapConstants.getMessage("mcare.complain.display.evalution"));
      out.write("\", dataIndex: 'evalution',sortable: false,width:50},\r\n");
      out.write("       \t   \t\t\t{ text: \"");
      out.print(UnieapConstants.getMessage("mcare.complain.display.text"));
      out.write("\", dataIndex: 'text',flex: true, sortable: false,width:500,\r\n");
      out.write("\t\t       \t   \t  \trenderer: function (value, meta, record){\r\n");
      out.write("\t\t\t\t\t\t\tvar max = 150;\r\n");
      out.write("\t\t\t\t\t\t\tmeta.tdAttr = 'data-qtip=\"' + value + '\"';\r\n");
      out.write("\t\t\t\t\t\t\treturn value.length < max ? value : value.substring(0, max - 3) + '...';\r\n");
      out.write("\t\t\t\t\t\t}\t\r\n");
      out.write("       \t   \t\t\t},\r\n");
      out.write("       \t   \t\t\t{ text: \"");
      out.print(UnieapConstants.getMessage("mcare.complain.display.feedback"));
      out.write("\", dataIndex: 'feedback',flex: true, sortable: false,width:500,\r\n");
      out.write("\t\t       \t   \t  \trenderer: function (value, meta, record){\r\n");
      out.write("\t\t\t\t\t\t\tvar max = 150;\r\n");
      out.write("\t\t\t\t\t\t\tmeta.tdAttr = 'data-qtip=\"' + value + '\"';\r\n");
      out.write("\t\t\t\t\t\t\treturn value.length < max ? value : value.substring(0, max - 3) + '...';\r\n");
      out.write("\t\t\t\t\t\t}\t\r\n");
      out.write("       \t   \t\t\t},\r\n");
      out.write("\t\t\t       \t{ text: \"");
      out.print(UnieapConstants.getMessage("mcare.complain.display.url"));
      out.write("\", dataIndex: 'url', sortable: false,width:150,\r\n");
      out.write("\t       \t   \t\t\trenderer: function (value, meta, record){\r\n");
      out.write("\t       \t   \t\t\t\tif(value!=null&&value!=''){\r\n");
      out.write("\t       \t   \t\t\t\t\tvar fileName = record.get(\"fileName\");\r\n");
      out.write("\t       \t   \t\t\t\t\tmeta.tdAttr = 'data-qtip=\"' + fileName + '\"';\r\n");
      out.write("\t\t\t\t\t\t\t\treturn '<span style=\"margin-right:10px\"><a href=\"#\"  onclick=showPicture(\"'+value+'\")>'+fileName+'</a></span>';\r\n");
      out.write("\t       \t   \t\t\t\t}else{\r\n");
      out.write("\t       \t   \t\t\t\t\treturn '';\r\n");
      out.write("\t       \t   \t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t}\t\r\n");
      out.write("\t\t\t       \t},\r\n");
      out.write("\t\t\t       \t{ text: \"");
      out.print(UnieapConstants.getMessage("mcare.complain.display.submitDate"));
      out.write("\", dataIndex: 'submitDate', sortable: false,width:120},\r\n");
      out.write("\t\t\t       \t{ text: \"");
      out.print(UnieapConstants.getMessage("mcare.complain.display.submitBy"));
      out.write("\", dataIndex: 'submitBy', sortable: false,width:100},\r\n");
      out.write("\t\t\t       \t{ text: \"");
      out.print(UnieapConstants.getMessage("comm.status"));
      out.write("\", dataIndex: 'statusDesc', sortable: false,width:100}\r\n");
      out.write("       \t   \t   \t],\r\n");
      out.write("\t       \t   \ttbar:[queryform],\r\n");
      out.write("           \t   \tbbar:new Ext.PagingToolbar(\r\n");
      out.write("           \t   \t{ store : gridstore,displayInfo: true})\r\n");
      out.write("            });\r\n");
      out.write("       datagrid.render();\r\n");
      out.write("\t   var dataWin = null;\r\n");
      out.write("       var dataForm = null;\r\n");
      out.write("       var operType = '';\r\n");
      out.write("       function showForm(status,selectedRecord){\r\n");
      out.write("        \toperType = status;\r\n");
      out.write("            if (dataWin==null){\r\n");
      out.write("            \tdataForm = Ext.widget('form',\r\n");
      out.write("            \t{\r\n");
      out.write("                    defaults:{labelAlign: 'left', labelWidth: 90, anchor: '100%'},\r\n");
      out.write("                    bodyPadding:5,\r\n");
      out.write("                    items:\r\n");
      out.write("                    [\r\n");
      out.write("                    \t{xtype:'fieldset', title:'");
      out.print(UnieapConstants.getMessage("comm.data"));
      out.write("',\r\n");
      out.write("\t                        items:\r\n");
      out.write("\t                        [\r\n");
      out.write("\t                        \t{ xtype:'textfield',hidden: true, name:'id'},\r\n");
      out.write("\t                        \t{ xtype:'textfield',labelWidth:100, width:400, name:'evalution',fieldLabel:'");
      out.print(UnieapConstants.getMessage("mcare.complain.display.evalution"));
      out.write("',maxLength:45,allowBlank:false},\r\n");
      out.write("\t                        \t{ xtype:'textareafield',labelWidth:100, width:400, name:'text',fieldLabel:'");
      out.print(UnieapConstants.getMessage("mcare.complain.display.text"));
      out.write("',maxLength:255,growMin:60,growMax:100,allowBlank:false},\r\n");
      out.write("\t                        \t{ xtype:'textfield',labelWidth:100, width:400, name:'submitDate',fieldLabel:'");
      out.print(UnieapConstants.getMessage("mcare.complain.display.submitDate"));
      out.write("',maxLength:45,allowBlank:false},\r\n");
      out.write("\t                        \t{ xtype:'textfield',labelWidth:100, width:400, name:'submitBy',fieldLabel:'");
      out.print(UnieapConstants.getMessage("mcare.complain.display.submitBy"));
      out.write("',maxLength:45,allowBlank:false},\r\n");
      out.write("\t                        \t{ xtype:'textareafield',labelWidth:100, width:400, name:'feedback',fieldLabel:'");
      out.print(UnieapConstants.getMessage("mcare.complain.display.feedback"));
      out.write("',maxLength:255,growMin:60,growMax:100,allowBlank:false}\r\n");
      out.write("\t                        ]\r\n");
      out.write("\t                    }\r\n");
      out.write("                    ],\r\n");
      out.write("                    buttons: \r\n");
      out.write("                    [\r\n");
      out.write("\t                    {id:'formCancel', text: '");
      out.print(UnieapConstants.getMessage("comm.cancel"));
      out.write("',\r\n");
      out.write("\t                        handler: function(){\r\n");
      out.write("\t                        \tdataForm.getForm().reset();\r\n");
      out.write("\t                        \tdataWin.hide();\r\n");
      out.write("\t                        }\r\n");
      out.write("\t                    }, \r\n");
      out.write("\t                    {id:'formSubmit',text: '");
      out.print(UnieapConstants.getMessage("comm.submit"));
      out.write("',\r\n");
      out.write("\t                        handler: function(){\r\n");
      out.write("\t                        \tvar form = dataForm.getForm();\r\n");
      out.write("\t                        \t if (form.isValid()){\r\n");
      out.write("\t                                 form.submit({\r\n");
      out.write("\t                                     clientValidation: true,\r\n");
      out.write("\t                                     method: 'POST',\r\n");
      out.write("\t                                     params:{'operType':operType},\r\n");
      out.write("\t                                     waitMsg: '");
      out.print(UnieapConstants.getMessage("comm.processing"));
      out.write("',\r\n");
      out.write("\t                                     url: 'easyMobileController.do?method=complainDeal',\r\n");
      out.write("\t                                     success: function(form, action) {\r\n");
      out.write("\t                                    \tvar result = Ext.JSON.decode(action.response.responseText);\r\n");
      out.write("\t\t\t\t\t\t                    if(result.isSuccess == 'failed'){\r\n");
      out.write("\t\t\t\t\t\t                    \tExt.MessageBox.show({title: '");
      out.print(UnieapConstants.getMessage("comm.status"));
      out.write("',msg:result.message,\r\n");
      out.write("\t\t                                 \t\t\tbuttons: Ext.MessageBox.OK,icon:Ext.MessageBox.ERROR});\r\n");
      out.write("\t\t\t\t\t\t                    }else{\r\n");
      out.write(" \t\t                                    \tExt.MessageBox.show({title: '");
      out.print(UnieapConstants.getMessage("comm.status"));
      out.write("',msg:'");
      out.print(UnieapConstants.getMessage("comm.success.save"));
      out.write("',fn: showResult,\r\n");
      out.write("\t \t\t                               \t\t\tbuttons: Ext.MessageBox.OK,icon:Ext.MessageBox.INFO});\r\n");
      out.write("\t\t\t\t\t\t                    }\r\n");
      out.write("\t                                     },\r\n");
      out.write("\t                                     failure: function(form, action){\r\n");
      out.write("\t                                    \t Ext.MessageBox.show({title: '");
      out.print(UnieapConstants.getMessage("comm.status"));
      out.write("',msg:action.response.responseText,\r\n");
      out.write("\t                                 \t\t\tbuttons: Ext.MessageBox.OK,icon:Ext.MessageBox.ERROR});\r\n");
      out.write("\t                                     }\r\n");
      out.write("\t                                 });\r\n");
      out.write("\t                        \t }\r\n");
      out.write("\t                        }\r\n");
      out.write("\t                    }\r\n");
      out.write("                    ]\r\n");
      out.write("                });\r\n");
      out.write("                dataWin = Ext.widget('window', \r\n");
      out.write("                { title: '");
      out.print(UnieapConstants.getMessage("comm.data"));
      out.write("', closeAction: 'hide', width: 480, height: 300, layout: 'fit', modal: true, items: dataForm,defaultFocus: 'reply' });\r\n");
      out.write("            }\r\n");
      out.write("            if(operType=='Add'){\r\n");
      out.write("            \tdataForm.getForm().reset();\r\n");
      out.write("            \tdataWin.show();\r\n");
      out.write("            }else if(operType=='Modify'){\r\n");
      out.write("            \tdataWin.show();\r\n");
      out.write("            \tdataForm.getForm().reset();\r\n");
      out.write("            \tdataForm.getForm().findField('evalution').setReadOnly(true);\r\n");
      out.write("            \tdataForm.getForm().findField('evalution').inputEl.addCls('readonly_field');\r\n");
      out.write("            \tdataForm.getForm().findField('text').setReadOnly(true);\r\n");
      out.write("            \tdataForm.getForm().findField('text').inputEl.addCls('readonly_field');\r\n");
      out.write("            \tdataForm.getForm().findField('submitDate').setReadOnly(true);\r\n");
      out.write("            \tdataForm.getForm().findField('submitDate').inputEl.addCls('readonly_field');\r\n");
      out.write("            \tdataForm.getForm().findField('submitBy').setReadOnly(true);\r\n");
      out.write("            \tdataForm.getForm().findField('submitBy').inputEl.addCls('readonly_field');\r\n");
      out.write("            \tdataForm.getForm().setValues(selectedRecord.data);\r\n");
      out.write("            }else{\r\n");
      out.write("            \tdataWin.show();\r\n");
      out.write("            }\r\n");
      out.write("\t    }\r\n");
      out.write("\t\tfunction showResult(btn){\r\n");
      out.write("\t     \tdataWin.hide();\r\n");
      out.write("\t     \tgridstore.reload();\r\n");
      out.write("\t    }\r\n");
      out.write("\t});\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"datagrid\"></div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
