/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.23
 * Generated at: 2016-02-25 18:14:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.apps.mcare._360view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.util.*;
import com.unieap.UnieapConstants;
import com.apps.esb.service.bss.vo.macre.customerprofile.CustomerProfileVO;

public final class usagehistory_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/unieap/unieap_unlogin.jsp", Long.valueOf(1456419423342L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.apps.esb.service.bss.vo.macre.customerprofile.CustomerProfileVO");
    _jspx_imports_classes.add("com.unieap.UnieapConstants");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');

    String path = request.getContextPath();
	String basePath = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort()
	+ path + "/";

      out.write("\r\n");
      out.write("<link href=\"");
      out.print(path);
      out.write("/apps/mcare/mcare.css\" type=\"text/css\" rel=\"stylesheet\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/unieap/js/jquery/jquery-2.2.0.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar basePathUrl = \"");
      out.print(basePath);
      out.write("\";\r\n");
      out.write("\t$(document).ready(function () { \r\n");
      out.write("\t\tShowbo.Msg.hide();\r\n");
      out.write("\t}); \r\n");
      out.write("</script>\r\n");
      out.write("<!-- unieap用户权限文件 -->\r\n");
      out.write("<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("<meta http-equiv=\"expires\" content=\"0\">\r\n");
      out.write("<meta http-equiv=\"keywords\" content=\"mobile care,mobile service,self-service\">\r\n");
      out.write("<meta http-equiv=\"description\" content=\"unieap system\">\t\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no\">    \r\n");
      out.write("<meta name=\"format-detection\" content=\"telephone=no\" /> \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	CustomerProfileVO vo = (CustomerProfileVO) session.getAttribute(UnieapConstants.USER);

      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(path);
      out.write("/unieap/js/jquery/plugins/chosen_v1.4.2/chosen.css\">\r\n");
      out.write("<script src=\"");
      out.print(path);
      out.write("/unieap/js/jquery/plugins/chosen_v1.4.2/chosen.jquery.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(path);
      out.write("/unieap/js/jquery/plugins/Guriddo_jqGrid_JS_5.0.2/css/ui.jqgrid.css\">\r\n");
      out.write("<script src=\"");
      out.print(path);
      out.write("/unieap/js/jquery/plugins/Guriddo_jqGrid_JS_5.0.2/js/jquery.jqGrid.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".monthList {\r\n");
      out.write("\twidth: 50px;\r\n");
      out.write("\theight: 50px;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\t$(\"#serviceCategory\").chosen({});\r\n");
      out.write("\t});\r\n");
      out.write("\t$( \"#startDate\" ).datepicker({\r\n");
      out.write("\t\tinline: false\r\n");
      out.write("\t});\r\n");
      out.write("\t$( \"#endDate\" ).datepicker({\r\n");
      out.write("\t\tinline: true\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tjQuery('#grid').jqGrid({\r\n");
      out.write("\t\thoverrows:false,\r\n");
      out.write("\t\t\"viewrecords\":true,\r\n");
      out.write("\t\t\"jsonReader\":{\"repeatitems\":false,\"subgrid\":{\"repeatitems\":false}},\r\n");
      out.write("\t\t\"gridview\":true,\r\n");
      out.write("\t\t\"url\":\"");
      out.print(path);
      out.write("/mCareController.do?method=getUsageHistoryList\",\r\n");
      out.write("\t\t\"loadonce\": true,\r\n");
      out.write("\t\t\"rowNum\":10,\r\n");
      out.write("\t\t\"height\":200,\r\n");
      out.write("\t\t\"autowidth\":true,\r\n");
      out.write("\t\t//\"sortname\":\"OrderID\",\r\n");
      out.write("\t\t\"rowList\":[10,30,40],\r\n");
      out.write("\t\t\"datatype\":\"json\",\r\n");
      out.write("\t\t\"colModel\":[\r\n");
      out.write("\t\t\t{\"name\":\"Call Type\",\"index\":\"flowType\",\"sorttype\":\"string\",\"search\":false,\"editable\":false},\r\n");
      out.write("\t\t\t{\"name\":\"Service No.\",\"index\":\"serviceNumber\",\"sorttype\":\"string\",\"search\":false,\"editable\":false},\r\n");
      out.write("\t\t\t{\"name\":\"Service Type\",\"index\":\"serviceTypeName\",\"sorttype\":\"string\",\"search\":false,\"editable\":false},\r\n");
      out.write("\t\t\t{\"name\":\"Start Time\",\"index\":\"startTime\",\"sorttype\":\"datetime\",\"formatter\":\"date\",\r\n");
      out.write("\t\t\t\t\"formatoptions\":{\"srcformat\":\"Y-m-d H:i:s\",\"newformat\":\"m/d/Y\"},\r\n");
      out.write("\t\t\t\t\"search\":false,\"editable\":false\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t{\"name\":\"Charge Amount\",\"index\":\"actualChargeAmt\",\"sorttype\":\"string\",\"search\":false,\"editable\":false},\r\n");
      out.write("\t\t\t{\"name\":\"Duration\",\"index\":\"actualVolume\",\"sorttype\":\"string\",\"search\":false,\"editable\":false},\r\n");
      out.write("\t\t\t{\"name\":\"Volume\",\"index\":\"actualVolume\",\"sorttype\":\"string\",\"search\":false,\"editable\":false},\r\n");
      out.write("\t\t\t{\"name\":\"Measure Unit\",\"index\":\"measureUnit\",\"sorttype\":\"string\",\"search\":false,\"editable\":false},\r\n");
      out.write("\t\t\t{\"name\":\"Offering Name\",\"index\":\"offeringName\",\"sorttype\":\"string\",\"search\":false,\"editable\":false}\r\n");
      out.write("\t\t],\r\n");
      out.write("\t\t\"pager\":\"#pager\"\r\n");
      out.write("\t});\r\n");
      out.write("\t// Toolbar searching\r\n");
      out.write("\t//jQuery('#grid').jqGrid('filterToolbar',{\"stringResult\":true});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<div class=\"bizPageDisplay\">\r\n");
      out.write("\t<div class=\"bizPageTitle\">\r\n");
      out.write("\t\t<span class=\"bizPageTitleFont\">>>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${menuTitle}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"fl\">\r\n");
      out.write("\t\t<div class=\"img\">\r\n");
      out.write("\t\t\t<img src=\"");
      out.print(path);
      out.write("/apps/mcare/images/ACCOUNTS_BALANCE_SEARCH.png\"\r\n");
      out.write("\t\t\t\talt=\"my balance\" width=\"120\" />\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"desc\">\r\n");
      out.write("\t\t<div class=\"optionsDesc\">Query usage history that include call details, rental details etc; based on privacy request SMS verification code.</div>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<span class=\"color_6\">My Name : </span><font class='descTitle1'>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${customerName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</font>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<span class=\"color_6\">Service Number : </span><font\r\n");
      out.write("\t\t\t\tclass='descTitle1'>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${serviceNumber}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</font>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class='cl'></div>\r\n");
      out.write("\t<div style=\"border-top: 1px solid #00e1e1\"></div>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<span class=\"displayListTitle\">Query Usage Per Duration</span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"tableDispalyOneField\"><span class=\"tableDispalyField\">Service Category</span></td>\r\n");
      out.write("\t\t\t\t<td colspan='5'>\r\n");
      out.write("\t\t\t\t\t<select id=\"serviceCategory\" data-placeholder=\"Choose a Country...\" class=\"chosen-select\" multiple style=\"width:350px;\" tabindex=\"4\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"\"></option>\r\n");
      out.write("\t\t            \t<option value=\"United States\">United States</option>\r\n");
      out.write("\t\t            \t<option value=\"United Kingdom\">United Kingdom</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"tableDispalyOneField\"><span class=\"tableDispalyField\">Start Date</span></td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<input id=\"startDate\"  class=\"inputText l mr5\" type=\"text\" value=\"\" />\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td class=\"tableDispalyOneField\"><span class=\"tableDispalyField\">End Date</span></td>\r\n");
      out.write("\t\t\t\t<td colspan='2'>\r\n");
      out.write("\t\t\t\t\t<input id=\"endDate\" class=\"inputText l mr5\" type=\"text\"  value=\"\" />\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<input id=\"sbmtButton\" class=\"inputBut\" type=\"button\" tabindex=\"4\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"Query\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<div style=\"border-top: 1px solid #00e1e1\"></div>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<span class=\"displayListTitle\">Usage Details</span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<table id='grid'></table>\r\n");
      out.write("\t\t<div id='pager'></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
