package com.apps.mcare.pojo;
// Generated 2015-10-31 16:55:27 by Hibernate Tools 4.3.1

import java.util.Date;

import org.springframework.util.StringUtils;

import com.unieap.CacheMgt;
import com.unieap.mdm.vo.DicDataVO;

/**
 * AppOffering generated by hbm2java
 */
public class AppOffering implements java.io.Serializable {

	private Integer id;
	private String offeringId;
	private String offeringCode;
	private String offeringName;
	private String seq;
	private String offeringType;
	private String offeringTypeDesc;
	private String offeringDesc;
	private String effectiveType;
	private String effectiveTypeDesc;
	private String feeAmount;
	private Integer categoryId;
	private String activeFlag;
	private String activeFlagDesc;
	private Date createDate;
	private String createBy;
	private Date modifyDate;
	private String modifyBy;
	private String remark;

	public AppOffering() {
	}

	public AppOffering(Integer id, String offeringId, String offeringName, String offeringType, String effectiveType,
			Integer categoryId, String activeFlag, Date createDate, String createBy) {
		this.id = id;
		this.offeringId = offeringId;
		this.offeringName = offeringName;
		this.offeringType = offeringType;
		this.effectiveType = effectiveType;
		this.categoryId = categoryId;
		this.activeFlag = activeFlag;
		this.createDate = createDate;
		this.createBy = createBy;
	}

	public AppOffering(Integer id, String offeringId, String offeringCode, String offeringName, String seq,
			String offeringType, String offeringDesc, String effectiveType, String feeAmount, Integer categoryId,
			String activeFlag, Date createDate, String createBy, Date modifyDate, String modifyBy, String remark) {
		this.id = id;
		this.offeringId = offeringId;
		this.offeringCode = offeringCode;
		this.offeringName = offeringName;
		this.seq = seq;
		this.offeringType = offeringType;
		this.offeringDesc = offeringDesc;
		this.effectiveType = effectiveType;
		this.feeAmount = feeAmount;
		this.categoryId = categoryId;
		this.activeFlag = activeFlag;
		this.createDate = createDate;
		this.createBy = createBy;
		this.modifyDate = modifyDate;
		this.modifyBy = modifyBy;
		this.remark = remark;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getOfferingId() {
		return this.offeringId;
	}

	public void setOfferingId(String offeringId) {
		this.offeringId = offeringId;
	}

	public String getOfferingCode() {
		return this.offeringCode;
	}

	public void setOfferingCode(String offeringCode) {
		this.offeringCode = offeringCode;
	}

	public String getOfferingName() {
		return this.offeringName;
	}

	public void setOfferingName(String offeringName) {
		this.offeringName = offeringName;
	}

	public String getSeq() {
		return this.seq;
	}

	public void setSeq(String seq) {
		this.seq = seq;
	}

	public String getOfferingType() {
		return this.offeringType;
	}

	public void setOfferingType(String offeringType) {
		this.offeringType = offeringType;
		if(!StringUtils.isEmpty(this.offeringType)){
			DicDataVO dic =  CacheMgt.getDicData("offeringType",offeringType);
			if(dic!=null){
				this.offeringTypeDesc = dic.getDicName();
			}
		}
	}

	public String getOfferingDesc() {
		return this.offeringDesc;
	}

	public void setOfferingDesc(String offeringDesc) {
		this.offeringDesc = offeringDesc;
	}

	public String getEffectiveType() {
		return this.effectiveType;
	}

	public void setEffectiveType(String effectiveType) {
		this.effectiveType = effectiveType;
		if(!StringUtils.isEmpty(this.effectiveType)){
			DicDataVO dic =  CacheMgt.getDicData("effectMode",effectiveType);
			if(dic!=null){
				this.effectiveTypeDesc = dic.getDicName();
			}
		}
	}

	public String getFeeAmount() {
		return this.feeAmount;
	}

	public void setFeeAmount(String feeAmount) {
		this.feeAmount = feeAmount;
	}

	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	public String getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(String activeFlag) {
		this.activeFlag = activeFlag;
		if(!StringUtils.isEmpty(this.activeFlag)){
			DicDataVO dic =  CacheMgt.getDicData("activeFlag",activeFlag);
			if(dic!=null){
				this.activeFlagDesc = dic.getDicName();
			}
		}
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	public String getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getActiveFlagDesc() {
		return activeFlagDesc;
	}

	public void setActiveFlagDesc(String activeFlagDesc) {
		this.activeFlagDesc = activeFlagDesc;
	}

	public String getEffectiveTypeDesc() {
		return effectiveTypeDesc;
	}

	public void setEffectiveTypeDesc(String effectiveTypeDesc) {
		this.effectiveTypeDesc = effectiveTypeDesc;
	}

	public String getOfferingTypeDesc() {
		return offeringTypeDesc;
	}

	public void setOfferingTypeDesc(String offeringTypeDesc) {
		this.offeringTypeDesc = offeringTypeDesc;
	}

}
