package com.apps.mcare.pojo;
// Generated 2015-11-9 9:37:41 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * AppPushedList generated by hbm2java
 */
public class AppPushedList implements java.io.Serializable {

	private int id;
	private String imei;
	private String serviceNumber;
	private Date createDate;
	private String pushType;

	public AppPushedList() {
	}

	public AppPushedList(int id, String imei, Date createDate, String pushType) {
		this.id = id;
		this.imei = imei;
		this.createDate = createDate;
		this.pushType = pushType;
	}
	public AppPushedList(int id, String imei, Date createDate, String pushType,String serviceNumber) {
		this.id = id;
		this.imei = imei;
		this.createDate = createDate;
		this.pushType = pushType;
		this.serviceNumber = serviceNumber;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getImei() {
		return this.imei;
	}

	public void setImei(String imei) {
		this.imei = imei;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getPushType() {
		return this.pushType;
	}

	public void setPushType(String pushType) {
		this.pushType = pushType;
	}

	public String getServiceNumber() {
		return serviceNumber;
	}

	public void setServiceNumber(String serviceNumber) {
		this.serviceNumber = serviceNumber;
	}

}
