package com.apps.mcare.pojo;
// Generated 2015-10-18 15:09:28 by Hibernate Tools 4.3.1

import java.util.Date;

import org.springframework.util.StringUtils;

import com.unieap.CacheMgt;
import com.unieap.mdm.vo.DicDataVO;

/**
 * AppResconfig generated by hbm2java
 */
public class AppResconfig implements java.io.Serializable {

	private Integer id;
	private String type;
	private String name;
	private String text;
	private String subject;
	private String url;
	private String hyperlink;
	private String groupName;
	private String resolution;
	private String activeFlag;
	private String activeFlagDesc;
	private String pageNum;
	private Date modifyDate;
	private String seq;
	private String modifyBy;
	private String language;
	private String remark;
	private String attri1;
	private String attri2;

	public AppResconfig() {
	}

	public AppResconfig(Integer id, String type, String name) {
		this.id = id;
		this.type = type;
		this.name = name;
	}

	public AppResconfig(Integer id, String type, String name, String text, String subject, String url, String hyperlink,
			String groupName, String activeFlag, String pageNum, Date modifyDate, String seq, String modifyBy,
			String language, String remark,String resolution,String attri1,String attri2) {
		this.id = id;
		this.type = type;
		this.name = name;
		this.text = text;
		this.subject = subject;
		this.url = url;
		this.hyperlink = hyperlink;
		this.groupName = groupName;
		this.activeFlag = activeFlag;
		this.pageNum = pageNum;
		this.modifyDate = modifyDate;
		this.seq = seq;
		this.modifyBy = modifyBy;
		this.language = language;
		this.remark = remark;
		this.resolution = resolution;
		this.attri1 = attri1;
		this.attri2 = attri2;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getHyperlink() {
		return this.hyperlink;
	}

	public void setHyperlink(String hyperlink) {
		this.hyperlink = hyperlink;
	}

	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	public String getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(String activeFlag) {
		this.activeFlag = activeFlag;
		if(!StringUtils.isEmpty(this.activeFlag)){
			DicDataVO dic =  CacheMgt.getDicData("activeFlag",activeFlag);
			if(dic!=null){
				this.activeFlagDesc = dic.getDicName();
			}
		}
	}

	public String getPageNum() {
		return this.pageNum;
	}

	public void setPageNum(String pageNum) {
		this.pageNum = pageNum;
	}

	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	public String getSeq() {
		return this.seq;
	}

	public void setSeq(String seq) {
		this.seq = seq;
	}

	public String getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getActiveFlagDesc() {
		return activeFlagDesc;
	}

	public void setActiveFlagDesc(String activeFlagDesc) {
		this.activeFlagDesc = activeFlagDesc;
	}

	public String getResolution() {
		return resolution;
	}

	public void setResolution(String resolution) {
		this.resolution = resolution;
	}

	public String getAttri1() {
		return attri1;
	}

	public void setAttri1(String attri1) {
		this.attri1 = attri1;
	}

	public String getAttri2() {
		return attri2;
	}

	public void setAttri2(String attri2) {
		this.attri2 = attri2;
	}

}
