package com.apps.mcare.pojo;
// Generated 2015-10-3 8:06:26 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * AppShop generated by hbm2java
 */
public class AppShop implements java.io.Serializable {

	private Integer id;
	private String cityId;
	private String cityName;
	private String shopName;
	private String openTime;
	private String shopNo;
	private String address;
	private String longitude;
	private String latitude;
	private String activeFlag;
	private Date createDate;
	private String createBy;
	private Date modifyDate;
	private String modifyBy;
	private String remark;
	private String tenantId;

	public AppShop() {
	}

	public AppShop(Integer id, String cityId, String cityName, String shopName, String openTime, String address,
			String activeFlag, Date createDate, String createBy) {
		this.id = id;
		this.cityId = cityId;
		this.cityName = cityName;
		this.shopName = shopName;
		this.openTime = openTime;
		this.address = address;
		this.activeFlag = activeFlag;
		this.createDate = createDate;
		this.createBy = createBy;
	}

	public AppShop(Integer id, String cityId, String cityName, String shopName, String openTime, String shopNo,
			String address, String longitude, String latitude, String activeFlag, Date createDate, String createBy,
			Date modifyDate, String modifyBy, String remark,String tenantId) {
		this.id = id;
		this.cityId = cityId;
		this.cityName = cityName;
		this.shopName = shopName;
		this.openTime = openTime;
		this.shopNo = shopNo;
		this.address = address;
		this.longitude = longitude;
		this.latitude = latitude;
		this.activeFlag = activeFlag;
		this.createDate = createDate;
		this.createBy = createBy;
		this.modifyDate = modifyDate;
		this.modifyBy = modifyBy;
		this.remark = remark;
		this.tenantId = tenantId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCityId() {
		return this.cityId;
	}

	public void setCityId(String cityId) {
		this.cityId = cityId;
	}

	public String getCityName() {
		return this.cityName;
	}

	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

	public String getShopName() {
		return this.shopName;
	}

	public void setShopName(String shopName) {
		this.shopName = shopName;
	}

	public String getOpenTime() {
		return this.openTime;
	}

	public void setOpenTime(String openTime) {
		this.openTime = openTime;
	}

	public String getShopNo() {
		return this.shopNo;
	}

	public void setShopNo(String shopNo) {
		this.shopNo = shopNo;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	public String getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(String activeFlag) {
		this.activeFlag = activeFlag;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	public String getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getTenantId() {
		return tenantId;
	}

	public void setTenantId(String tenantId) {
		this.tenantId = tenantId;
	}

}
