package com.apps.mcare.pojo;
// Generated 2015-11-9 9:37:41 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * AppUpgrade generated by hbm2java
 */
public class AppUpgrade implements java.io.Serializable {

	private int id;
	private String activeFlag;
	private String version;
	private String changeDesc;
	private Date createDate;
	private String remark;

	public AppUpgrade() {
	}

	public AppUpgrade(int id, String activeFlag) {
		this.id = id;
		this.activeFlag = activeFlag;
	}

	public AppUpgrade(int id, String activeFlag, String version, String changeDesc, Date createDate, String remark) {
		this.id = id;
		this.activeFlag = activeFlag;
		this.version = version;
		this.changeDesc = changeDesc;
		this.createDate = createDate;
		this.remark = remark;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(String activeFlag) {
		this.activeFlag = activeFlag;
	}

	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	public String getChangeDesc() {
		return this.changeDesc;
	}

	public void setChangeDesc(String changeDesc) {
		this.changeDesc = changeDesc;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
