package com.apps.reuse.pojo;
// default package
// Generated 2015-7-15 0:41:03 by Hibernate Tools 4.3.1

/**
 * Area generated by hbm2java
 */
public class Area implements java.io.Serializable {

	private String code;
	private String name;
	private String path;
	private Integer level;

	public Area() {
	}

	public Area(String code) {
		this.code = code;
	}

	public Area(String code, String name, String path, Integer level) {
		this.code = code;
		this.name = name;
		this.path = path;
		this.level = level;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	public Integer getLevel() {
		return this.level;
	}

	public void setLevel(Integer level) {
		this.level = level;
	}

}
