package com.apps.reuse.pojo;

// default package
// Generated 2015-7-5 13:01:00 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * ReuseAsses generated by hbm2java
 */
public class ReuseAsses implements java.io.Serializable {

	private Integer assesId;
	private Integer productId;
	private Date assesDate;
	private String amount;
	private String status;

	public ReuseAsses() {
	}

	public ReuseAsses(Integer assesId, Integer productId, Date assesDate, String amount) {
		this.assesId = assesId;
		this.productId = productId;
		this.assesDate = assesDate;
		this.amount = amount;
	}

	public ReuseAsses(Integer assesId, Integer productId, Date assesDate, String amount, String status) {
		this.assesId = assesId;
		this.productId = productId;
		this.assesDate = assesDate;
		this.amount = amount;
		this.status = status;
	}

	public Integer getAssesId() {
		return this.assesId;
	}

	public void setAssesId(Integer assesId) {
		this.assesId = assesId;
	}

	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	public Date getAssesDate() {
		return this.assesDate;
	}

	public void setAssesDate(Date assesDate) {
		this.assesDate = assesDate;
	}

	public String getAmount() {
		return this.amount;
	}

	public void setAmount(String amount) {
		this.amount = amount;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
