package com.apps.reuse.pojo;
// default package
// Generated 2015-7-5 13:01:00 by Hibernate Tools 4.3.1

import java.util.Date;

import org.springframework.util.StringUtils;

import com.unieap.CacheMgt;
import com.unieap.mdm.vo.DicDataVO;

/**
 * ReuseCustomer generated by hbm2java
 */
public class ReuseCustomer implements java.io.Serializable {

	private Integer customerId;
	private String customerCode;
	private String customerName;
	private String sex;
	private String sexDesc;
	private String phone;
	private String email;
	private String wechat;
	private String remark;
	private Date createDate;
	private Date modifyDate;
	private String createBy;
	private String modifyBy;

	public ReuseCustomer() {
	}

	public ReuseCustomer(Integer customerId, String customerCode, Date createDate, String createBy,String sex) {
		this.customerId = customerId;
		this.customerCode = customerCode;
		this.createDate = createDate;
		this.createBy = createBy;
		this.sex = sex;
	}

	public ReuseCustomer(Integer customerId, String customerCode, String customerName, String sex, String phone,
			String email, String remark, Date createDate, Date modifyDate, String createBy, String modifyBy,String wechat) {
		this.customerId = customerId;
		this.customerCode = customerCode;
		this.customerName = customerName;
		this.sex = sex;
		this.phone = phone;
		this.email = email;
		this.wechat = wechat;
		this.remark = remark;
		this.createDate = createDate;
		this.modifyDate = modifyDate;
		this.createBy = createBy;
		this.modifyBy = modifyBy;
	}

	public Integer getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	public String getCustomerCode() {
		return this.customerCode;
	}

	public void setCustomerCode(String customerCode) {
		this.customerCode = customerCode;
	}

	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	public String getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	public String getWechat() {
		return wechat;
	}

	public void setWechat(String wechat) {
		this.wechat = wechat;
	}

	public String getSex() {
		return sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
		if(!StringUtils.isEmpty(this.sex)){
			DicDataVO dic =  CacheMgt.getDicData("5745",sex);
			if(dic!=null){
				this.sexDesc = dic.getDicName();
			}
		}
	}

	public String getSexDesc() {
		return sexDesc;
	}

	public void setSexDesc(String sexDesc) {
		this.sexDesc = sexDesc;
	}

	
	
}
