package com.apps.reuse.pojo;
// default package
// Generated 2015-7-5 13:01:00 by Hibernate Tools 4.3.1

import java.util.Date;

import org.springframework.util.StringUtils;

import com.unieap.CacheMgt;
import com.unieap.mdm.vo.DicDataVO;

/**
 * ReuseProductTracking generated by hbm2java
 */
public class ReuseProductTracking implements java.io.Serializable {

	private Integer trackingId;
	private Integer productId;
	private String status;
	private String statusDesc;
	private String referNo;
	private String updatedBy;
	private Date createDate;
	private Date modifyDate;
	private String createBy;
	private String modifyBy;
	private String remark;

	public ReuseProductTracking() {
	}

	public ReuseProductTracking(Integer trackingId, Integer productId, String status, Date createDate, String createBy) {
		this.trackingId = trackingId;
		this.productId = productId;
		this.status = status;
		this.createDate = createDate;
		this.createBy = createBy;
	}

	public ReuseProductTracking(Integer trackingId, Integer productId, String status, String updatedBy, Date createDate,
			Date modifyDate, String createBy, String modifyBy, String remark,String referNo) {
		this.trackingId = trackingId;
		this.productId = productId;
		this.status = status;
		this.updatedBy = updatedBy;
		this.createDate = createDate;
		this.modifyDate = modifyDate;
		this.createBy = createBy;
		this.modifyBy = modifyBy;
		this.remark = remark;
		this.referNo = referNo;
	}

	public Integer getTrackingId() {
		return this.trackingId;
	}

	public void setTrackingId(Integer trackingId) {
		this.trackingId = trackingId;
	}

	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
		if(!StringUtils.isEmpty(this.status)){
			DicDataVO dic =  CacheMgt.getDicData("5478",status);
			if(dic!=null){
				this.statusDesc = dic.getDicName();
			}
		}
	}

	public String getStatusDesc() {
		return statusDesc;
	}

	public void setStatusDesc(String statusDesc) {
		this.statusDesc = statusDesc;
	}

	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	public String getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getReferNo() {
		return referNo;
	}

	public void setReferNo(String referNo) {
		this.referNo = referNo;
	}
	

}
