package com.apps.reuse.pojo;
// default package
// Generated 2015-7-8 0:38:43 by Hibernate Tools 4.3.1

/**
 * ReuseProductDetail generated by hbm2java
 */
public class ReuseProductDetail implements java.io.Serializable {

	private Integer detailId;
	private Integer productId;
	private String attributeName;
	private String attributeValue;

	public ReuseProductDetail() {
	}

	public ReuseProductDetail(Integer detailId, Integer productId, String attributeName) {
		this.detailId = detailId;
		this.productId = productId;
		this.attributeName = attributeName;
	}

	public ReuseProductDetail(Integer detailId, Integer productId, String attributeName, String attributeValue) {
		this.detailId = detailId;
		this.productId = productId;
		this.attributeName = attributeName;
		this.attributeValue = attributeValue;
	}

	public Integer getDetailId() {
		return this.detailId;
	}

	public void setDetailId(Integer detailId) {
		this.detailId = detailId;
	}

	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	public String getAttributeName() {
		return this.attributeName;
	}

	public void setAttributeName(String attributeName) {
		this.attributeName = attributeName;
	}

	public String getAttributeValue() {
		return this.attributeValue;
	}

	public void setAttributeValue(String attributeValue) {
		this.attributeValue = attributeValue;
	}

}
