package com.apps.reuse.pojo;
// default package
// Generated 2015-7-5 13:01:00 by Hibernate Tools 4.3.1

import java.util.Date;

import org.springframework.util.StringUtils;

import com.unieap.CacheMgt;
import com.unieap.mdm.vo.DicDataVO;

/**
 * ReuseProduct generated by hbm2java
 */
public class ReuseProduct implements java.io.Serializable {

	private Integer customerId;
	private Integer productId;
	private String productCode;
	private String productName;
	private String brand;
	private String brandDesc;
	private String model;
	private String modelDesc;
	private String color;
	private String colorDesc;
	private String memery;
	private String memeryDesc;
	private String version;
	private String versionDesc;
	private String warranty;
	private String warrantyDesc;
	private String maintainance;
	private String maintainanceDesc;
	private String icloudStatus;
	private String icloudStatusDesc;
	private String productProfile;
	private String productProfileDesc;
	private String inWater;
	private String inWaterDesc;
	private String assesAmount;
	private String saleAmount;
	private String status;
	private String statusDesc;
	private String remark;
	private Date createDate;
	private Date modifyDate;
	private String createBy;
	private String modifyBy;
	
	public ReuseProduct() {
	}

	public ReuseProduct(Integer customerId, Integer productId, Date createDate, String createBy,String productCode) {
		this.customerId = customerId;
		this.productId = productId;
		this.createDate = createDate;
		this.createBy = createBy;
		this.productCode = productCode;
	}

	public ReuseProduct(Integer customerId, Integer productId, String productName, String brand, String model, String color,
			String memery, String version, String warranty, String maintainance, String icloudStatus,
			String productProfile, String inWater, String assesAmount, String saleAmount, String status, String remark,
			Date createDate, Date modifyDate, String createBy,String modifyBy,String productCode) {
		this.customerId = customerId;
		this.productId = productId;
		this.productName = productName;
		this.brand = brand;
		this.model = model;
		this.color = color;
		this.memery = memery;
		this.version = version;
		this.warranty = warranty;
		this.maintainance = maintainance;
		this.icloudStatus = icloudStatus;
		this.productProfile = productProfile;
		this.inWater = inWater;
		this.assesAmount = assesAmount;
		this.saleAmount = saleAmount;
		this.status = status;
		this.remark = remark;
		this.createDate = createDate;
		this.modifyDate = modifyDate;
		this.createBy = createBy;
		this.modifyBy = modifyBy;
		this.productCode = productCode;
	}
	
	
	public Integer getCustomerId() {
		return customerId;
	}
	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}
	public Integer getProductId() {
		return productId;
	}
	public void setProductId(Integer productId) {
		this.productId = productId;
	}
	public String getProductName() {
		return productName;
	}
	public void setProductName(String productName) {
		this.productName = productName;
	}
	public String getBrand() {
		return brand;
	}
	public void setBrand(String brand) {
		this.brand = brand;
		if(!StringUtils.isEmpty(this.brand)){
			DicDataVO dic =  CacheMgt.getDicData("5060",brand);
			if(dic!=null){
				this.brandDesc = dic.getDicName();
			}
		}
	}
	public String getBrandDesc() {
		return brandDesc;
	}
	public void setBrandDesc(String brandDesc) {
		this.brandDesc = brandDesc;
	}
	public String getModel() {
		return model;
	}
	public void setModel(String model) {
		this.model = model;
		if(!StringUtils.isEmpty(this.model)){
			DicDataVO dic =  CacheMgt.getDicData("5065",model);
			if(dic!=null){
				this.modelDesc = dic.getDicName();
			}
		}
	}
	public String getModelDesc() {
		return modelDesc;
	}
	public void setModelDesc(String modelDesc) {
		this.modelDesc = modelDesc;
	}
	public String getColor() {
		return color;
	}
	public void setColor(String color) {
		this.color = color;
		if(!StringUtils.isEmpty(this.color)){
			DicDataVO dic =  CacheMgt.getDicData("5064",color);
			if(dic!=null){
				this.colorDesc = dic.getDicName();
			}
		}
	}
	public String getColorDesc() {
		return colorDesc;
	}
	public void setColorDesc(String colorDesc) {
		this.colorDesc = colorDesc;
	}
	public String getMemery() {
		return memery;
	}
	public void setMemery(String memery) {
		this.memery = memery;
		if(!StringUtils.isEmpty(this.memery)){
			DicDataVO dic =  CacheMgt.getDicData("5467",memery);
			if(dic!=null){
				this.memeryDesc = dic.getDicName();
			}
		}
	}
	public String getMemeryDesc() {
		return memeryDesc;
	}
	public void setMemeryDesc(String memeryDesc) {
		this.memeryDesc = memeryDesc;
	}
	public String getVersion() {
		return version;
	}
	public void setVersion(String version) {
		this.version = version;
		if(!StringUtils.isEmpty(this.version)){
			DicDataVO dic =  CacheMgt.getDicData("5473",version);
			if(dic!=null){
				this.versionDesc = dic.getDicName();
			}
		}
	}
	public String getVersionDesc() {
		return versionDesc;
	}
	public void setVersionDesc(String versionDesc) {
		this.versionDesc = versionDesc;
	}
	public String getWarranty() {
		return warranty;
	}
	public void setWarranty(String warranty) {
		this.warranty = warranty;
		if(!StringUtils.isEmpty(this.warranty)){
			DicDataVO dic =  CacheMgt.getDicData("5474",warranty);
			if(dic!=null){
				this.warrantyDesc = dic.getDicName();
			}
		}
	}
	public String getWarrantyDesc() {
		return warrantyDesc;
	}
	public void setWarrantyDesc(String warrantyDesc) {
		this.warrantyDesc = warrantyDesc;
	}
	public String getMaintainance() {
		return maintainance;
	}
	public void setMaintainance(String maintainance) {
		this.maintainance = maintainance;
		if(!StringUtils.isEmpty(this.maintainance)){
			DicDataVO dic =  CacheMgt.getDicData("5475",maintainance);
			if(dic!=null){
				this.maintainanceDesc = dic.getDicName();
			}
		}
	}
	public String getMaintainanceDesc() {
		return maintainanceDesc;
	}
	public void setMaintainanceDesc(String maintainanceDesc) {
		this.maintainanceDesc = maintainanceDesc;
	}
	public String getIcloudStatus() {
		return icloudStatus;
	}
	public void setIcloudStatus(String icloudStatus) {
		this.icloudStatus = icloudStatus;
		if(!StringUtils.isEmpty(this.icloudStatus)){
			DicDataVO dic =  CacheMgt.getDicData("1001",icloudStatus);
			if(dic!=null){
				this.icloudStatusDesc = dic.getDicName();
			}
		}
	}
	public String getIcloudStatusDesc() {
		return icloudStatusDesc;
	}
	public void setIcloudStatusDesc(String icloudStatusDesc) {
		this.icloudStatusDesc = icloudStatusDesc;
	}
	public String getProductProfile() {
		return productProfile;
	}
	public void setProductProfile(String productProfile) {
		this.productProfile = productProfile;
		if(!StringUtils.isEmpty(this.productProfile)){
			DicDataVO dic =  CacheMgt.getDicData("5477",productProfile);
			if(dic!=null){
				this.productProfileDesc = dic.getDicName();
			}
		}
	}
	public String getProductProfileDesc() {
		return productProfileDesc;
	}
	public void setProductProfileDesc(String productProfileDesc) {
		this.productProfileDesc = productProfileDesc;
	}
	public String getInWater() {
		return inWater;
	}
	public void setInWater(String inWater) {
		this.inWater = inWater;
		if(!StringUtils.isEmpty(this.inWater)){
			DicDataVO dic =  CacheMgt.getDicData("1001",inWater);
			if(dic!=null){
				this.inWaterDesc = dic.getDicName();
			}
		}
	}
	public String getInWaterDesc() {
		return inWaterDesc;
	}
	public void setInWaterDesc(String inWaterDesc) {
		this.inWaterDesc = inWaterDesc;
	}
	public String getAssesAmount() {
		return assesAmount;
	}
	public void setAssesAmount(String assesAmount) {
		this.assesAmount = assesAmount;
	}
	public String getSaleAmount() {
		return saleAmount;
	}
	public void setSaleAmount(String saleAmount) {
		this.saleAmount = saleAmount;
	}
	public String getStatus() {
		return status;
	}
	public void setStatus(String status) {
		this.status = status;
		if(!StringUtils.isEmpty(this.status)){
			DicDataVO dic =  CacheMgt.getDicData("5478",status);
			if(dic!=null){
				this.statusDesc = dic.getDicName();
			}
		}
	}
	public String getStatusDesc() {
		return statusDesc;
	}
	public void setStatusDesc(String statusDesc) {
		this.statusDesc = statusDesc;
	}
	public String getRemark() {
		return remark;
	}
	public void setRemark(String remark) {
		this.remark = remark;
	}
	public Date getCreateDate() {
		return createDate;
	}
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}
	public Date getModifyDate() {
		return modifyDate;
	}
	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}
	public String getCreateBy() {
		return createBy;
	}
	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}
	public String getModifyBy() {
		return modifyBy;
	}
	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	public String getProductCode() {
		return productCode;
	}

	public void setProductCode(String productCode) {
		this.productCode = productCode;
	}
	

}
