package com.unieap.pojo;
// Generated 2015-9-11 13:43:49 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * DicDataTree generated by hbm2java
 */
public class DicDataTree implements java.io.Serializable {

	private Integer dicId;
	private String dicCode;
	private String dicName;
	private Integer parentId;
	private String parentCode;
	private String parentName;
	private String dicType;
	private String leaf;
	private Integer seq;
	private String href;
	private String icon;
	private String activeFlag;
	private String remark;
	private String language;
	private Date createDate;
	private Date modifyDate;
	private String createBy;
	private String modifyBy;
	private String tenantId;

	public DicDataTree() {
	}

	public DicDataTree(Integer dicId, String dicCode, String dicName, String leaf, String activeFlag, Date createDate,
			String createBy,String tenantId) {
		this.dicId = dicId;
		this.dicCode = dicCode;
		this.dicName = dicName;
		this.leaf = leaf;
		this.activeFlag = activeFlag;
		this.createDate = createDate;
		this.createBy = createBy;
		this.tenantId = tenantId;
	}

	public DicDataTree(Integer dicId, String dicCode, String dicName, Integer parentId, String parentCode,
			String parentName,String dicType, String leaf, Integer seq, String href, String icon, String activeFlag, String remark,
			String language, Date createDate, Date modifyDate, String createBy, String modifyBy,String tenantId) {
		this.dicId = dicId;
		this.dicCode = dicCode;
		this.dicName = dicName;
		this.parentId = parentId;
		this.parentCode = parentCode;
		this.parentName = parentName;
		this.dicType = dicType;
		this.leaf = leaf;
		this.seq = seq;
		this.href = href;
		this.icon = icon;
		this.activeFlag = activeFlag;
		this.remark = remark;
		this.language = language;
		this.createDate = createDate;
		this.modifyDate = modifyDate;
		this.createBy = createBy;
		this.modifyBy = modifyBy;
		this.tenantId = tenantId;
	}

	public Integer getDicId() {
		return this.dicId;
	}

	public void setDicId(Integer dicId) {
		this.dicId = dicId;
	}

	public String getDicCode() {
		return this.dicCode;
	}

	public void setDicCode(String dicCode) {
		this.dicCode = dicCode;
	}

	public String getDicName() {
		return this.dicName;
	}

	public void setDicName(String dicName) {
		this.dicName = dicName;
	}

	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	public String getParentCode() {
		return this.parentCode;
	}

	public void setParentCode(String parentCode) {
		this.parentCode = parentCode;
	}

	public String getParentName() {
		return this.parentName;
	}

	public String getDicType() {
		return dicType;
	}

	public void setDicType(String dicType) {
		this.dicType = dicType;
	}

	public void setParentName(String parentName) {
		this.parentName = parentName;
	}

	public String getLeaf() {
		return this.leaf;
	}

	public void setLeaf(String leaf) {
		this.leaf = leaf;
	}

	public Integer getSeq() {
		return this.seq;
	}

	public void setSeq(Integer seq) {
		this.seq = seq;
	}

	public String getHref() {
		return this.href;
	}

	public void setHref(String href) {
		this.href = href;
	}

	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	public String getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(String activeFlag) {
		this.activeFlag = activeFlag;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	public String getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	public String getTenantId() {
		return tenantId;
	}

	public void setTenantId(String tenantId) {
		this.tenantId = tenantId;
	}

}
