package com.unieap.pojo;
// Generated 2015-10-24 14:14:02 by Hibernate Tools 4.3.1

/**
 * ErrorCode generated by hbm2java
 */
public class ErrorCode implements java.io.Serializable {

	private int id;
	private String version;
	private String errorCode;
	private String errorDesc;
	private String application;
	private String billingCode;
	private String billingDesc;
	private String language;
	private String remark;

	public ErrorCode() {
	}

	public ErrorCode(int id) {
		this.id = id;
	}

	public ErrorCode(int id, String version, String errorCode, String errorDesc, String application, String billingCode,
			String billingDesc, String language, String remark) {
		this.id = id;
		this.version = version;
		this.errorCode = errorCode;
		this.errorDesc = errorDesc;
		this.application = application;
		this.billingCode = billingCode;
		this.billingDesc = billingDesc;
		this.language = language;
		this.remark = remark;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	public String getErrorCode() {
		return this.errorCode;
	}

	public void setErrorCode(String errorCode) {
		this.errorCode = errorCode;
	}

	public String getErrorDesc() {
		return this.errorDesc;
	}

	public void setErrorDesc(String errorDesc) {
		this.errorDesc = errorDesc;
	}

	public String getApplication() {
		return this.application;
	}

	public void setApplication(String application) {
		this.application = application;
	}

	public String getBillingCode() {
		return this.billingCode;
	}

	public void setBillingCode(String billingCode) {
		this.billingCode = billingCode;
	}

	public String getBillingDesc() {
		return this.billingDesc;
	}

	public void setBillingDesc(String billingDesc) {
		this.billingDesc = billingDesc;
	}

	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
