package com.unieap.pojo;
// default package
// Generated 2015-8-8 16:02:23 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * ExLog generated by hbm2java
 */
public class ExLog implements java.io.Serializable {

	private int id;
	private String operator;
	private Date operationDate;
	private String exType;
	private String bizModule;
	private String exCode;
	private String exInfo;
	private byte[] exTracking;

	public ExLog() {
	}

	public ExLog(int id, String operator, Date operationDate, String exType, String bizModule) {
		this.id = id;
		this.operator = operator;
		this.operationDate = operationDate;
		this.exType = exType;
		this.bizModule = bizModule;
	}

	public ExLog(int id, String operator, Date operationDate, String exType, String bizModule, String exCode,
			String exInfo, byte[] exTracking) {
		this.id = id;
		this.operator = operator;
		this.operationDate = operationDate;
		this.exType = exType;
		this.bizModule = bizModule;
		this.exCode = exCode;
		this.exInfo = exInfo;
		this.exTracking = exTracking;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	public Date getOperationDate() {
		return this.operationDate;
	}

	public void setOperationDate(Date operationDate) {
		this.operationDate = operationDate;
	}

	public String getExType() {
		return this.exType;
	}

	public void setExType(String exType) {
		this.exType = exType;
	}

	public String getBizModule() {
		return this.bizModule;
	}

	public void setBizModule(String bizModule) {
		this.bizModule = bizModule;
	}

	public String getExCode() {
		return this.exCode;
	}

	public void setExCode(String exCode) {
		this.exCode = exCode;
	}

	public String getExInfo() {
		return this.exInfo;
	}

	public void setExInfo(String exInfo) {
		this.exInfo = exInfo;
	}

	public byte[] getExTracking() {
		return this.exTracking;
	}

	public void setExTracking(byte[] exTracking) {
		this.exTracking = exTracking;
	}

}
