package com.unieap.pojo;
// Generated 2015-10-18 15:09:28 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * FileArchive generated by hbm2java
 */
public class FileArchive implements java.io.Serializable {

	private Integer id;
	private String fileName;
	private String fileType;
	private Double fileSize;
	private String filePath;
	private String url;
	private String extKey;
	private String fileCategory;
	private Date archiveDate;
	private String remark;

	public FileArchive() {
	}

	public FileArchive(Integer id, String fileName, String fileType, String filePath, String extKey, Date archiveDate) {
		this.id = id;
		this.fileName = fileName;
		this.fileType = fileType;
		this.filePath = filePath;
		this.extKey = extKey;
		this.archiveDate = archiveDate;
	}

	public FileArchive(Integer id, String fileName, String fileType, Double fileSize, String filePath, String extKey,
			String fileCategory, Date archiveDate, String remark,String url) {
		this.id = id;
		this.fileName = fileName;
		this.fileType = fileType;
		this.fileSize = fileSize;
		this.filePath = filePath;
		this.extKey = extKey;
		this.fileCategory = fileCategory;
		this.archiveDate = archiveDate;
		this.remark = remark;
		this.url = url;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public String getFileType() {
		return this.fileType;
	}

	public void setFileType(String fileType) {
		this.fileType = fileType;
	}

	public Double getFileSize() {
		return this.fileSize;
	}

	public void setFileSize(Double fileSize) {
		this.fileSize = fileSize;
	}

	public String getFilePath() {
		return this.filePath;
	}

	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}

	public String getExtKey() {
		return this.extKey;
	}

	public void setExtKey(String extKey) {
		this.extKey = extKey;
	}

	public String getFileCategory() {
		return this.fileCategory;
	}

	public void setFileCategory(String fileCategory) {
		this.fileCategory = fileCategory;
	}

	public Date getArchiveDate() {
		return this.archiveDate;
	}

	public void setArchiveDate(Date archiveDate) {
		this.archiveDate = archiveDate;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

}
