package com.unieap.pojo;
// Generated 2016-4-8 0:19:40 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Monitor generated by hbm2java
 */
public class Monitor implements java.io.Serializable {

	private int id;
	private Date executeDate;
	private String bizType;
	private String systemName;
	private String executeResult;
	private String executeResultDesc;
	private Date createDate;
	private String remark;

	public Monitor() {
	}

	public Monitor(int id, Date executeDate, String bizType, String systemName, String executeResult, Date createDate) {
		this.id = id;
		this.executeDate = executeDate;
		this.bizType = bizType;
		this.systemName = systemName;
		this.executeResult = executeResult;
		this.createDate = createDate;
	}

	public Monitor(int id, Date executeDate, String bizType, String systemName, String executeResult,
			String executeResultDesc, Date createDate, String remark) {
		this.id = id;
		this.executeDate = executeDate;
		this.bizType = bizType;
		this.systemName = systemName;
		this.executeResult = executeResult;
		this.executeResultDesc = executeResultDesc;
		this.createDate = createDate;
		this.remark = remark;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Date getExecuteDate() {
		return this.executeDate;
	}

	public void setExecuteDate(Date executeDate) {
		this.executeDate = executeDate;
	}

	public String getBizType() {
		return this.bizType;
	}

	public void setBizType(String bizType) {
		this.bizType = bizType;
	}

	public String getSystemName() {
		return this.systemName;
	}

	public void setSystemName(String systemName) {
		this.systemName = systemName;
	}

	public String getExecuteResult() {
		return this.executeResult;
	}

	public void setExecuteResult(String executeResult) {
		this.executeResult = executeResult;
	}

	public String getExecuteResultDesc() {
		return this.executeResultDesc;
	}

	public void setExecuteResultDesc(String executeResultDesc) {
		this.executeResultDesc = executeResultDesc;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
