package com.unieap.pojo;
// Generated 2015-9-29 13:36:22 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * SmsVerfiy generated by hbm2java
 */
public class SmsVerfiy implements java.io.Serializable {

	private Integer id;
	private String type;
	private String fromBy;
	private String sendTo;
	private String content;
	private String verifyCode;
	private Date sendDate;
	private String checked;

	public SmsVerfiy() {
	}

	public SmsVerfiy(Integer id, String type, String fromBy, String sendTo, String content, String verifyCode, Date sendDate,
			String checked) {
		this.id = id;
		this.type = type;
		this.fromBy = fromBy;
		this.sendTo = sendTo;
		this.content = content;
		this.verifyCode = verifyCode;
		this.sendDate = sendDate;
		this.checked = checked;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	

	public String getFromBy() {
		return fromBy;
	}

	public void setFromBy(String fromBy) {
		this.fromBy = fromBy;
	}

	public String getSendTo() {
		return sendTo;
	}

	public void setSendTo(String sendTo) {
		this.sendTo = sendTo;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getVerifyCode() {
		return this.verifyCode;
	}

	public void setVerifyCode(String verifyCode) {
		this.verifyCode = verifyCode;
	}

	public Date getSendDate() {
		return this.sendDate;
	}

	public void setSendDate(Date sendDate) {
		this.sendDate = sendDate;
	}

	public String getChecked() {
		return this.checked;
	}

	public void setChecked(String checked) {
		this.checked = checked;
	}

}
