package com.apps.reuse.vo;
// default package
// Generated 2015-7-14 21:38:33 by Hibernate Tools 4.3.1

import java.util.Date;

import org.springframework.util.StringUtils;

import com.unieap.CacheMgt;
import com.unieap.mdm.vo.DicDataVO;

/**
 * ReuseCustomerAddress generated by hbm2java
 */
public class ReuseCustomerAddressVO implements java.io.Serializable {

	private Integer addressId;
	private Integer customerId;
	private String type;
	private String typeDesc;
	private String defaultFlag;
	private String defaultFlagDesc;
	private String province;
	private String provinceDesc;
	private String city;
	private String cityDesc;
	private String district;
	private String districtDesc;
	private String street;
	private String streetDesc;
	private String postcode;
	private String contact;
	private String address1;
	private String address2;
	private Date createDate;
	private String createBy;
	private Date modifyDate;
	private String modifyBy;
	private String phone;

	
	public Integer getAddressId() {
		return this.addressId;
	}

	public void setAddressId(Integer addressId) {
		this.addressId = addressId;
	}

	public Integer getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
		if(!StringUtils.isEmpty(this.type)){
			DicDataVO dic =  CacheMgt.getDicData("5209",type);
			if(dic!=null){
				this.typeDesc = dic.getDicName();
			}
		}
	}

	public String getTypeDesc() {
		return typeDesc;
	}

	public String getDefaultFlag() {
		return this.defaultFlag;
	}

	public void setDefaultFlag(String defaultFlag) {
		this.defaultFlag = defaultFlag;
		if(!StringUtils.isEmpty(this.defaultFlag)){
			DicDataVO dic =  CacheMgt.getDicData("1001",defaultFlag);
			if(dic!=null){
				this.defaultFlagDesc = dic.getDicName();
			}
		}
	}

	
	public String getDefaultFlagDesc() {
		return defaultFlagDesc;
	}

	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getDistrict() {
		return this.district;
	}

	public void setDistrict(String district) {
		this.district = district;
	}

	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	public String getPostcode() {
		return this.postcode;
	}

	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}

	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	public String getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getProvinceDesc() {
		return provinceDesc;
	}

	public void setProvinceDesc(String provinceDesc) {
		this.provinceDesc = provinceDesc;
	}

	public String getCityDesc() {
		return cityDesc;
	}

	public void setCityDesc(String cityDesc) {
		this.cityDesc = cityDesc;
	}

	public String getDistrictDesc() {
		return districtDesc;
	}

	public void setDistrictDesc(String districtDesc) {
		this.districtDesc = districtDesc;
	}

	public String getStreetDesc() {
		return streetDesc;
	}

	public void setStreetDesc(String streetDesc) {
		this.streetDesc = streetDesc;
	}

	public void setTypeDesc(String typeDesc) {
		this.typeDesc = typeDesc;
	}

	public void setDefaultFlagDesc(String defaultFlagDesc) {
		this.defaultFlagDesc = defaultFlagDesc;
	}

}
