package com.apps.esb.pojo;
// Generated 2015-9-20 23:58:33 by Hibernate Tools 4.3.1

/**
 * EsbInfo generated by hbm2java
 */
public class EsbInfo implements java.io.Serializable {

	private int id;
	private String bizCode;
	private String infName;
	private String url;
	private String activeFlag;

	public EsbInfo() {
	}

	public EsbInfo(int id, String bizCode, String url) {
		this.id = id;
		this.bizCode = bizCode;
		this.url = url;
	}

	public EsbInfo(int id, String bizCode, String infName, String url, String activeFlag) {
		this.id = id;
		this.bizCode = bizCode;
		this.infName = infName;
		this.url = url;
		this.activeFlag = activeFlag;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getBizCode() {
		return this.bizCode;
	}

	public void setBizCode(String bizCode) {
		this.bizCode = bizCode;
	}

	public String getInfName() {
		return this.infName;
	}

	public void setInfName(String infName) {
		this.infName = infName;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(String activeFlag) {
		this.activeFlag = activeFlag;
	}

}
