package com.apps.esb.pojo;
// Generated 2015-9-19 22:30:44 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Esblog generated by hbm2java
 */
public class Esblog implements java.io.Serializable {

	private int logId;
	private String channelCode;
	private String bizCode;
	private String serviceNumber;
	private String transactionId;
	private String requestTime;
	private String responseTime;
	private String systemCode;
	private String extTransactionId;
	private byte[] requestInfo;
	private byte[] responseInfo;
	private Date createDate;
	private String resultCode;
	private String resultDesc;
	private String executeTime;
	private String sourceSystem;
	private String destSystem;

	public Esblog() {
	}

	public Esblog(int logId) {
		this.logId = logId;
	}

	public Esblog(int logId, String channelCode, String bizCode, String serviceNumber, String transactionId,
			String requestTime, String responseTime, String systemCode, String extTransactionId, byte[] requestInfo,
			byte[] responseInfo, Date createDate, String resultCode, String resultDesc,String executeTime,
			String sourceSystem,String destSystem) {
		this.logId = logId;
		this.channelCode = channelCode;
		this.bizCode = bizCode;
		this.serviceNumber = serviceNumber;
		this.transactionId = transactionId;
		this.requestTime = requestTime;
		this.responseTime = responseTime;
		this.systemCode = systemCode;
		this.extTransactionId = extTransactionId;
		this.requestInfo = requestInfo;
		this.responseInfo = responseInfo;
		this.createDate = createDate;
		this.resultCode = resultCode;
		this.resultDesc = resultDesc;
		this.executeTime = executeTime;
		this.sourceSystem = sourceSystem;
		this.destSystem = destSystem;
	}

	public int getLogId() {
		return this.logId;
	}

	public void setLogId(int logId) {
		this.logId = logId;
	}

	public String getChannelCode() {
		return this.channelCode;
	}

	public void setChannelCode(String channelCode) {
		this.channelCode = channelCode;
	}

	public String getBizCode() {
		return this.bizCode;
	}

	public void setBizCode(String bizCode) {
		this.bizCode = bizCode;
	}

	public String getServiceNumber() {
		return this.serviceNumber;
	}

	public void setServiceNumber(String serviceNumber) {
		this.serviceNumber = serviceNumber;
	}

	public String getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(String transactionId) {
		this.transactionId = transactionId;
	}

	public String getRequestTime() {
		return this.requestTime;
	}

	public void setRequestTime(String requestTime) {
		this.requestTime = requestTime;
	}

	public String getResponseTime() {
		return this.responseTime;
	}

	public void setResponseTime(String responseTime) {
		this.responseTime = responseTime;
	}

	public String getSystemCode() {
		return this.systemCode;
	}

	public void setSystemCode(String systemCode) {
		this.systemCode = systemCode;
	}

	public String getExtTransactionId() {
		return this.extTransactionId;
	}

	public void setExtTransactionId(String extTransactionId) {
		this.extTransactionId = extTransactionId;
	}

	public byte[] getRequestInfo() {
		return this.requestInfo;
	}

	public void setRequestInfo(byte[] requestInfo) {
		this.requestInfo = requestInfo;
	}

	public byte[] getResponseInfo() {
		return this.responseInfo;
	}

	public void setResponseInfo(byte[] responseInfo) {
		this.responseInfo = responseInfo;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getResultCode() {
		return this.resultCode;
	}

	public void setResultCode(String resultCode) {
		this.resultCode = resultCode;
	}

	public String getResultDesc() {
		return this.resultDesc;
	}

	public void setResultDesc(String resultDesc) {
		this.resultDesc = resultDesc;
	}

	public String getExecuteTime() {
		return executeTime;
	}

	public void setExecuteTime(String executeTime) {
		this.executeTime = executeTime;
	}

	public String getSourceSystem() {
		return sourceSystem;
	}

	public void setSourceSystem(String sourceSystem) {
		this.sourceSystem = sourceSystem;
	}

	public String getDestSystem() {
		return destSystem;
	}

	public void setDestSystem(String destSystem) {
		this.destSystem = destSystem;
	}

}
