package com.apps.easymobile.pojo;
// Generated 2015-10-17 21:10:30 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * AppComplain generated by hbm2java
 */
public class AppComplain implements java.io.Serializable {

	private Integer id;
	private String evalution;
	private String text;
	private byte[] screenshot;
	private Date submitDate;
	private String submitBy;
	private String url;
	private Integer fileId;
	private String status;
	private Date modifyDate;
	private String modifyBy;
	private String remark;
	private String feedback;

	public AppComplain() {
	}

	public AppComplain(Integer id, String evalution, Date submitDate, String submitBy, String status) {
		this.id = id;
		this.evalution = evalution;
		this.submitDate = submitDate;
		this.submitBy = submitBy;
		this.status = status;
	}

	public AppComplain(Integer id, String evalution, String text, byte[] screenshot, Date submitDate, String submitBy,
			String status, Date modifyDate, String modifyBy, String remark,String feedback,Integer fileId,String url) {
		this.id = id;
		this.evalution = evalution;
		this.text = text;
		this.screenshot = screenshot;
		this.submitDate = submitDate;
		this.submitBy = submitBy;
		this.status = status;
		this.modifyDate = modifyDate;
		this.modifyBy = modifyBy;
		this.remark = remark;
		this.feedback = feedback;
		this.fileId = fileId;
		this.url = url;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getEvalution() {
		return this.evalution;
	}

	public void setEvalution(String evalution) {
		this.evalution = evalution;
	}

	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public byte[] getScreenshot() {
		return this.screenshot;
	}

	public void setScreenshot(byte[] screenshot) {
		this.screenshot = screenshot;
	}

	public Date getSubmitDate() {
		return this.submitDate;
	}

	public void setSubmitDate(Date submitDate) {
		this.submitDate = submitDate;
	}

	public String getSubmitBy() {
		return this.submitBy;
	}

	public void setSubmitBy(String submitBy) {
		this.submitBy = submitBy;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	public String getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getFeedback() {
		return feedback;
	}

	public void setFeedback(String feedback) {
		this.feedback = feedback;
	}

	public Integer getFileId() {
		return fileId;
	}

	public void setFileId(Integer fileId) {
		this.fileId = fileId;
	}

	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}
	

}
