package com.apps.easymobile.pojo;
// Generated 2015-10-17 21:10:30 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * AppComplainFile generated by hbm2java
 */
public class AppComplainFile implements java.io.Serializable {

	private Integer id;
	private Integer complainId;
	private String fileName;
	private Double fileSize;
	private String filePath;
	private Date createDate;

	public AppComplainFile() {
	}

	public AppComplainFile(Integer id, Integer complainId) {
		this.id = id;
		this.complainId = complainId;
	}

	public AppComplainFile(Integer id, Integer complainId, String fileName, Double fileSize, String filePath, Date createDate) {
		this.id = id;
		this.complainId = complainId;
		this.fileName = fileName;
		this.fileSize = fileSize;
		this.filePath = filePath;
		this.createDate = createDate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getComplainId() {
		return this.complainId;
	}

	public void setComplainId(Integer complainId) {
		this.complainId = complainId;
	}

	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public Double getFileSize() {
		return this.fileSize;
	}

	public void setFileSize(Double fileSize) {
		this.fileSize = fileSize;
	}

	public String getFilePath() {
		return this.filePath;
	}

	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
