package com.apps.easymobile.pojo;
// Generated 2015-11-9 9:37:41 by Hibernate Tools 4.3.1

import java.util.Date;

import org.springframework.util.StringUtils;

import com.unieap.CacheMgt;
import com.unieap.mdm.vo.DicDataVO;

/**
 * AppPushMessage generated by hbm2java
 */
public class AppDenomination implements java.io.Serializable {

	private Integer id;
	private Integer seq;
	private String type;
	private String typeDesc;
	private String value;
	private String denoValue;
	private String handleFee;
	private String attri1;
	private String attri2;
	private String activeFlag;
	private String activeFlagDesc;
	private String createBy;
	private Date createDate;
	private String modifyBy;
	private Date modifyDate;
	private String remark;
	private Date effectiveDate;
	private Date expiredDate;

	public AppDenomination() {
	}

	public AppDenomination(Integer id,Integer seq,String type, String activeFlag, String createBy, Date createDate) {
		this.id = id;
		this.seq = seq;
		this.type = type;
		this.activeFlag = activeFlag;
		this.createBy = createBy;
		this.createDate = createDate;
	}

	
	
	public AppDenomination(Integer id, Integer seq, String type, String value, String denoValue, String handleFee,
			String attri1, String attri2, String activeFlag, String activeFlagDesc, String createBy, Date createDate,
			String modifyBy, Date modifyDate, String remark,Date effectiveDate,Date expiredDate) {
		this.id = id;
		this.seq = seq;
		this.type = type;
		this.value = value;
		this.denoValue = denoValue;
		this.handleFee = handleFee;
		this.attri1 = attri1;
		this.attri2 = attri2;
		this.activeFlag = activeFlag;
		this.activeFlagDesc = activeFlagDesc;
		this.createBy = createBy;
		this.createDate = createDate;
		this.modifyBy = modifyBy;
		this.modifyDate = modifyDate;
		this.remark = remark;
		this.effectiveDate = effectiveDate;
		this.expiredDate = expiredDate;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getSeq() {
		return seq;
	}

	public void setSeq(Integer seq) {
		this.seq = seq;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
		if(!StringUtils.isEmpty(this.type)){
			DicDataVO dic =  CacheMgt.getDicData("denomination",type);
			if(dic!=null){
				this.typeDesc = dic.getDicName();
			}
		}
	}

	public String getValue() {
		return value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public String getDenoValue() {
		return denoValue;
	}

	public void setDenoValue(String denoValue) {
		this.denoValue = denoValue;
	}

	public String getHandleFee() {
		return handleFee;
	}

	public void setHandleFee(String handleFee) {
		this.handleFee = handleFee;
	}

	public String getAttri1() {
		return attri1;
	}

	public void setAttri1(String attri1) {
		this.attri1 = attri1;
	}

	public String getAttri2() {
		return attri2;
	}

	public void setAttri2(String attri2) {
		this.attri2 = attri2;
	}

	public String getActiveFlag() {
		return activeFlag;
	}

	public void setActiveFlag(String activeFlag) {
		this.activeFlag = activeFlag;
		if(!StringUtils.isEmpty(this.activeFlag)){
			DicDataVO dic =  CacheMgt.getDicData("activeFlag",activeFlag);
			if(dic!=null){
				this.activeFlagDesc = dic.getDicName();
			}
		}
	}

	public String getActiveFlagDesc() {
		return activeFlagDesc;
	}

	public void setActiveFlagDesc(String activeFlagDesc) {
		this.activeFlagDesc = activeFlagDesc;
	}

	public String getCreateBy() {
		return createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getModifyBy() {
		return modifyBy;
	}

	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	public Date getModifyDate() {
		return modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Date getEffectiveDate() {
		return effectiveDate;
	}

	public void setEffectiveDate(Date effectiveDate) {
		this.effectiveDate = effectiveDate;
	}

	public Date getExpiredDate() {
		return expiredDate;
	}

	public void setExpiredDate(Date expiredDate) {
		this.expiredDate = expiredDate;
	}

	public String getTypeDesc() {
		return typeDesc;
	}

	public void setTypeDesc(String typeDesc) {
		this.typeDesc = typeDesc;
	}

	
	
	
}
