package com.apps.easymobile.pojo;
// Generated 2015-11-9 9:37:41 by Hibernate Tools 4.3.1

import java.util.Date;

import org.springframework.util.StringUtils;

import com.unieap.CacheMgt;
import com.unieap.mdm.vo.DicDataVO;

/**
 * AppPushMessage generated by hbm2java
 */
public class AppSpecialNum implements java.io.Serializable {

	private Integer id;
	private String type;
	private String subject;
	private String text;
	private String activeFlag;
	private String activeFlagDesc;
	private String remark;

	public AppSpecialNum() {
	}

	public AppSpecialNum(Integer id,String type, String activeFlag) {
		this.id = id;
		this.type = type;
		this.activeFlag = activeFlag;
	}

	public AppSpecialNum(Integer id, String type,String subject, String text, String hyperlink, String activeFlag, String remark,
			Date createDate, String modifyBy, Date modifyDate,Date effectiveDate,Date expiredDate) {
		this.id = id;
		this.type = type;
		this.subject = subject;
		this.text = text;
		this.activeFlag = activeFlag;
		this.remark = remark;
	}

	

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getSubject() {
		return subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	public String getText() {
		return text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(String activeFlag) {
		this.activeFlag = activeFlag;
		if(!StringUtils.isEmpty(this.activeFlag)){
			DicDataVO dic =  CacheMgt.getDicData("activeFlag",activeFlag);
			if(dic!=null){
				this.activeFlagDesc = dic.getDicName();
			}
		}
	}

	
	public String getActiveFlagDesc() {
		return activeFlagDesc;
	}

	public void setActiveFlagDesc(String activeFlagDesc) {
		this.activeFlagDesc = activeFlagDesc;
	}
	
	
}
