SET SQL_SAFE_UPDATES = 0;
delete from app_complain;
delete from app_push_message;
delete from app_pushed_list;
delete from app_upgrade;
delete from chglog;
delete from email_send;
delete from esblog;
delete from esblog_device;
delete from exclog;
delete from sms_verfiy;
delete from sms_notify;
delete from visit_log;